### PR TITLE
Changed --routing for --mediation

### PR DESCRIPTION
**Pull request by afrancoc2000**
performance.py doesn't receive --routing it uses --mediation so the way it is, it crashes.

### CODE REVIEW

**Comment by swcurran** [comment]
Thanks for the update!  We're working on the next version of this course and much appreciate the update!

Thanks as well for the ACA-Py work you did on the Acme example -- great stuff!

**Comment by afrancoc2000** [comment]
Sure, glad I coud help :)

**Comment by afrancoc2000** [comment]
@swcurran you know, we should also change the line references [here](https://github.com/cloudcompass/ToIPLabs/blob/master/docs/LFS173x/MediatorLab.md#navigating-the-code) but the context of the paragraph changes because the code also includes the Faber agent and I didn't know how to include it, I'm creating another pull request with that change please tell me if the context I'm writing its right.

**Comment by swcurran** [comment]
Part of what I'm doing is to update all the line requests and associated narrative to the latest version of the code.  I'll continue to use a specific version, but a much newer one.  That's part of what I'm doing to update all of the labs.

**Comment by afrancoc2000** [comment]
I will close the pull request then. Thanks!

**Pull request merged**
